{% set name = "datarobot" %}
{% set version = "2.20.2" %}
{% set sha256 = "04302dd08250e965d60a80ba24c4b34549dd4859164e5061f6a4500b9639b7e2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - pandas >=0.15
    - pyyaml >=3.11
    - requests >=2.21
    - requests-toolbelt >=0.6
    - trafaret <2.0,>=0.7,!=1.1.0
    - urllib3 >=1.24

test:
  imports:
    - datarobot

about:
  home: https://www.datarobot.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: This client library is designed to support the DataRobot API.

  description: |
    datarobot is a client library for working with the <https://www.datarobot.com/> platform API.
  doc_url: https://datarobot-public-api-client.readthedocs-hosted.com

extra:
  recipe-maintainers:
    - daveblumstein
    - dsakagi
    - elatt
    - madmott
    - nott
    - peterhurford
    - mclapper3
