{% set name = "datarobot" %}
{% set version = "3.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4700065a45fe174b9e9246b0eedcaf10059ac2a465f1be2b079b79fbed143ce

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pytest-runner
  run:
    - python >=3.7
    - strenum
    - pandas >=0.15
    - numpy
    - pyyaml >=3.11
    - requests >=2.21
    - requests-toolbelt >=0.6
    - trafaret !=1.1.0,<2.2,>=0.7
    - urllib3 >=1.23
    - typing_extensions
    - python-dateutil
    - mypy_extensions
    - pytz

test:
  imports:
    - datarobot

about:
  home: https://www.datarobot.com/
  license: DataRobot Tool and Utility Agreement
  license_family: PROPRIETARY
  license_url: https://www.datarobot.com/wp-content/uploads/2021/07/DataRobot-Tool-and-Utility-Agreement.pdf
  license_file:
    - LICENSE.txt
  summary: This client library is designed to support the DataRobot API.
  description: |
    datarobot is a client library for working with the <https://www.datarobot.com/> platform API.
  doc_url: https://datarobot-public-api-client.readthedocs-hosted.com

extra:
  recipe-maintainers:
    - dsakagi
    - ajalon1
